// VIOLATION: Unused using directives (IDE0005)
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using System.Xml;
using System.Xml.Linq;
using CqDemoApp003.Models;

namespace CqDemoApp003.Utils;

/// <summary>
/// Report generation utility class.
/// INTENTIONAL VIOLATIONS:
/// - Unused using directives (System.IO, System.Net, System.Xml, etc.)
/// - Missing null checks on parameters (CA1062)
/// - String concatenation instead of interpolation (CA1834)
/// - Public fields instead of properties (CA1051)
/// - Inconsistent return types
/// </summary>
public class ReportGenerator
{
    // VIOLATION: Public field instead of property (CA1051)
    public string ReportTitle = "Employee Report";

    // VIOLATION: Public field instead of property (CA1051)
    public string GeneratedBy = "System";

    // VIOLATION: Public field instead of property (CA1051)
    public int MaxRows = 1000;

    // VIOLATION: Public field instead of property (CA1051)
    public bool IncludeHeaders = true;

    // VIOLATION: Missing null check on parameter (CA1062)
    public string GenerateEmployeeReport(List<Employee> employees)
    {
        // VIOLATION: String concatenation instead of interpolation
        string report = "";
        report = report + "=== " + ReportTitle + " ===" + Environment.NewLine;
        report = report + "Generated by: " + GeneratedBy + Environment.NewLine;
        report = report + "Date: " + DateTime.Now.ToString("yyyy-MM-dd") + Environment.NewLine;
        report = report + "Total Employees: " + employees.Count.ToString() + Environment.NewLine;
        report = report + "---" + Environment.NewLine;

        foreach (var emp in employees)
        {
            // VIOLATION: String concatenation instead of interpolation
            report = report + emp.Id.ToString() + " | ";
            report = report + emp.FirstName + " " + emp.LastName + " | ";
            report = report + emp.Department + " | ";
            report = report + emp.Title + " | ";
            report = report + "$" + emp.Salary.ToString("N2") + " | ";
            report = report + emp.Status + Environment.NewLine;
        }

        return report;
    }

    // VIOLATION: Missing null check on parameter (CA1062)
    public string GenerateDepartmentSummary(List<Employee> employees)
    {
        // VIOLATION: String concatenation instead of interpolation
        string summary = "";
        summary = summary + "=== Department Summary ===" + Environment.NewLine;

        var departments = employees.GroupBy(e => e.Department);

        foreach (var dept in departments)
        {
            // VIOLATION: String concatenation instead of interpolation
            summary = summary + "Department: " + dept.Key + Environment.NewLine;
            summary = summary + "  Head Count: " + dept.Count().ToString() + Environment.NewLine;
            summary = summary + "  Average Salary: $" + dept.Average(e => e.Salary).ToString("N2") + Environment.NewLine;
            summary = summary + "  Total Salary: $" + dept.Sum(e => e.Salary).ToString("N2") + Environment.NewLine;
            summary = summary + "  Min Salary: $" + dept.Min(e => e.Salary).ToString("N2") + Environment.NewLine;
            summary = summary + "  Max Salary: $" + dept.Max(e => e.Salary).ToString("N2") + Environment.NewLine;
            summary = summary + "---" + Environment.NewLine;
        }

        return summary;
    }

    // VIOLATION: Missing null check on parameter (CA1062)
    public string GeneratePayrollReport(List<PayrollRecord> records)
    {
        // VIOLATION: String concatenation instead of interpolation
        string report = "";
        report = report + "=== Payroll Report ===" + Environment.NewLine;
        report = report + "Generated: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + Environment.NewLine;
        report = report + "Records: " + records.Count.ToString() + Environment.NewLine;
        report = report + "---" + Environment.NewLine;

        decimal totalNet = 0;
        decimal totalTax = 0;

        foreach (var rec in records)
        {
            // VIOLATION: String concatenation instead of interpolation
            report = report + rec.EmployeeId.ToString() + " | ";
            report = report + rec.EmployeeName + " | ";
            report = report + rec.Department + " | ";
            report = report + "Base: $" + rec.BaseSalary.ToString("N2") + " | ";
            report = report + "Bonus: $" + rec.Bonus.ToString("N2") + " | ";
            report = report + "Tax: $" + rec.TaxAmount.ToString("N2") + " | ";
            report = report + "Net: $" + rec.NetPay.ToString("N2") + Environment.NewLine;

            totalNet += rec.NetPay;
            totalTax += rec.TaxAmount;
        }

        // VIOLATION: String concatenation instead of interpolation
        report = report + "---" + Environment.NewLine;
        report = report + "Total Net Pay: $" + totalNet.ToString("N2") + Environment.NewLine;
        report = report + "Total Tax Withheld: $" + totalTax.ToString("N2") + Environment.NewLine;

        return report;
    }

    // VIOLATION: Missing null check on parameter (CA1062)
    // VIOLATION: Method could be static (CA1822)
    public string FormatEmployeeName(Employee employee)
    {
        // VIOLATION: String concatenation instead of interpolation
        return employee.LastName + ", " + employee.FirstName;
    }

    // VIOLATION: Missing null check on parameter (CA1062)
    // VIOLATION: Method could be static (CA1822)
    public Dictionary<string, int> CountByStatus(List<Employee> employees)
    {
        var counts = new Dictionary<string, int>();

        foreach (var emp in employees)
        {
            if (counts.ContainsKey(emp.Status))
                counts[emp.Status]++;
            else
                counts[emp.Status] = 1;
        }

        return counts;
    }

    // VIOLATION: Method could be static (CA1822)
    public string GenerateCSVRow(string[] fields)
    {
        // VIOLATION: Missing null check on parameter (CA1062)
        // VIOLATION: String concatenation in a loop
        string row = "";
        for (int i = 0; i < fields.Length; i++)
        {
            if (i > 0)
                row = row + ",";
            // VIOLATION: String concatenation instead of interpolation
            row = row + "\"" + fields[i].Replace("\"", "\"\"") + "\"";
        }
        return row;
    }
}
